version: "3.9"

services:

  server:
    build: ./server
    environment:
      - DB_ENDPOINT=mongodb://root:admin@mongo:27017/
      - SECRET=supersecret
      - SUBDOMAIN=lunar-dream-13
      - PORT=3000
    ports:
      - 3000:3000

  backup:
    build: ./backup
    environment:
      - DB_ENDPOINT=mongodb://root:admin@mongo:27017/
      - DATA_DIR=/backup
      - DELAY=60
      - LIMIT=10
    volumes:
      - backup_data:/backup

  mongo:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://root:admin@mongo:27017/

  rclone:
    build: ./rclone
    volumes:
      - backup_data:/backup
    environment:
      - DELAY=1000

  firefox:
    build: ./firefox
    ports:
      - 5800:5800
    volumes:
      - firefox_data:/config:rw
    shm_size: '2gb'

volumes:
  backup_data: {}
  mongo_data: {}
  firefox_data: {}
